version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: test_elastic
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
